/**
 * Convert palette object to Empire theme CSS
 * Now generates PROPER dark themes matching your structure
 */
export function generateThemeCSS(palette, mode = 'light') {
    const isDark = mode === 'dark';

    // Dark mode adjustments
    const neutralHue = isDark ? 230 : 280; // Blue for dark, purple for light
    const neutralChroma = isDark ? 0.035 : 0.02;

    // Generate neutral scale based on mode
    const neutralScale = generateNeutralScale(neutralHue, neutralChroma, isDark);

    // Header with theme selector
    let css = `/* Empire Theme - ${mode} mode */\n`;
    css += `/* Generated by Empire Theme Builder */\n\n`;
    css += `[data-theme="${mode}"] {\n\n`;

    // Color scales - DARK MODE ADJUSTED
    for (const [category, colors] of Object.entries(palette)) {
        css += `  /* ${category.charAt(0).toUpperCase() + category.slice(1)} Colors */\n`;

        // Adjust colors for dark mode (lighter versions)
        const adjustedColors = isDark ? adjustColorsForDarkMode(colors) : colors;

        for (const [shade, value] of Object.entries(adjustedColors)) {
            css += `  --${category}-${shade}: ${value};\n`;
        }
        css += `\n`;
    }

    // Neutral colors
    css += `  /* Neutral Colors */\n`;
    for (const [shade, value] of Object.entries(neutralScale)) {
        css += `  --neutral-${shade}: ${value};\n`;
    }
    css += `\n`;

    // Semantic mappings
    css += `  /* Semantic Mappings */\n`;
    css += `  --color-bg: var(--neutral-0);\n`;
    css += `  --color-text: var(--neutral-900);\n`;
    css += `  --color-text-muted: var(--neutral-${isDark ? '400' : '500'});\n`;
    css += `  --color-border: var(--neutral-${isDark ? '700' : '300'});\n`;
    css += `  --color-bg-muted: var(--neutral-100);\n`;
    css += `  --color-primary: var(--primary-500);\n`;
    css += `  --color-primary-hover: color-mix(in srgb, var(--color-primary), ${isDark ? 'black' : 'white'} 10%);\n\n`;

    // Status colors
    if (palette.info) css += `  --color-info: var(--info-500);\n`;
    if (palette.success) css += `  --color-success: var(--success-500);\n`;
    if (palette.warning) css += `  --color-warning: var(--warning-500);\n`;
    if (palette.error) css += `  --color-error: var(--error-500);\n`;
    if (palette.secondary) css += `  --color-secondary: var(--secondary-500);\n`;
    if (palette.accent) css += `  --color-accent: var(--accent-500);\n\n`;

    // Button variables
    css += `  /* Button Variables */\n`;
    css += `  --color-btn-primary-bg: var(--primary-${isDark ? '700' : '600'});\n`;
    css += `  --color-btn-primary-text: var(--neutral-${isDark ? '900' : '0'});\n`;
    css += `  --color-btn-primary-hover: var(--primary-${isDark ? '900' : '700'});\n\n`;

    if (palette.secondary) {
        css += `  --color-btn-secondary-bg: var(--primary-${isDark ? '600' : '700'});\n`;
        css += `  --color-btn-secondary-text: var(--neutral-${isDark ? '900' : '0'});\n`;
        css += `  --color-btn-secondary-hover: var(--primary-${isDark ? '800' : '600'});\n\n`;
    }

    // Card variables
    css += `  /* Card Variables */\n`;
    css += `  --color-card-bg: var(--neutral-${isDark ? '800' : '0'});\n`;
    css += `  --color-card-border: var(--neutral-${isDark ? '700' : '200'});\n\n`;

    // Form variables
    css += `  /* Form Variables */\n`;
    css += `  --color-input-bg: var(--neutral-0);\n`;
    css += `  --color-input-border: var(--neutral-${isDark ? '300' : '300'});\n`;
    css += `  --color-input-text: var(--neutral-900);\n`;
    css += `  --color-input-placeholder: var(--neutral-${isDark ? '500' : '500'});\n\n`;

    // Validation states
    css += `  /* Validation States */\n`;
    if (palette.error) css += `  --color-input-error-border: var(--error-400);\n`;
    if (palette.success) css += `  --color-input-success-border: var(--success-400);\n`;

    css += `}\n`;

    return css;
}

/**
 * Generate neutral scale for theme
 */
function generateNeutralScale(hue, baseChroma, isDark) {
    const scale = {};

    // Dark mode: darker at low numbers, lighter at high numbers
    // Light mode: lighter at low numbers, darker at high numbers
    const lightnessMap = isDark ? {
        '0': 0.18,    // Darker
        '100': 0.24,
        '200': 0.30,
        '300': 0.38,
        '400': 0.46,
        '500': 0.56,
        '600': 0.66,
        '700': 0.76,
        '800': 0.86,
        '900': 0.96   // Lighter
    } : {
        '0': 1.00,    // White
        '100': 0.98,
        '200': 0.95,
        '300': 0.90,
        '400': 0.70,
        '500': 0.50,
        '600': 0.35,
        '700': 0.30,
        '800': 0.20,
        '900': 0.25   // Darker
    };

    for (const [shade, lightness] of Object.entries(lightnessMap)) {
        // Chroma decreases as we go darker/lighter
        const chroma = baseChroma * (1 - Math.abs(lightness - 0.5) * 0.5);
        scale[shade] = `oklch(${(lightness * 100).toFixed(0)}% ${chroma.toFixed(4)} ${hue})`;
    }

    return scale;
}

/**
 * Adjust colors for dark mode (make them lighter)
 */
function adjustColorsForDarkMode(colors) {
    const adjusted = {};

    for (const [shade, value] of Object.entries(colors)) {
        // Parse OKLCH
        const match = value.match(/oklch\(([\d.]+)% ([\d.]+) ([\d.]+)\)/);
        if (match) {
            let [, lightness, chroma, hue] = match;
            lightness = parseFloat(lightness);

            // For dark mode, make colors generally lighter
            // Scale adjustment: darker shades get bigger boost
            const shadeNum = parseInt(shade);
            const boost = shadeNum <= 500 ? 0.25 : 0.15;
            const newLightness = Math.min(95, lightness + (boost * 100));

            adjusted[shade] = `oklch(${newLightness.toFixed(1)}% ${chroma} ${hue})`;
        } else {
            adjusted[shade] = value;
        }
    }

    return adjusted;
}

/**
 * Download CSS as file
 */
export function downloadCSS(content, filename) {
    const blob = new Blob([content], { type: 'text/css' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
